### ISSUE TITLE
Webhooks Invalid Secret

### ISSUE THREAD

**Issue by Panoply** [donutdan4114/shopify#2]
I'm coping this error:` [Sat Jul 09 05:25:27 2016] [error] [client 127.0.0.1] Invalid webhook: Invalid webhook.` using PageKite locally for testing. Is there any settings I'm missing? All other requests work well, except incoming webhooks.

**Comment by septembermd** [comment]
@panoply what was wrong? how did you solve?

**Comment by panoply** [comment]
This was a while ago, but if memory calls me correct. I initially re-call boycotting PageKite and using [Ngrok](https://ngrok.com/) from here, I went through PHP Error Logs. I have a working controller using this package and webhooks, maybe it will help you. I am using a Dependency Inversion principle design pattern. Look for Webhooks classes, follow them. Hope this helps.

[github.com/panoply/silk-sync/blob/master/app/Http/Repositories/ShopifyRepository.php](https://github.com/panoply/silk-sync/blob/master/app/Http/Repositories/ShopifyRepository.php)
