### ISSUE TITLE
Shopify API version depreciated in 2020

### ISSUE THREAD

**Issue by joehuggans** [donutdan4114/shopify#21]
Hi, there.

We have just received an email from Shopify stating that:-

Shopify API version 2019-04 on will be removed on April 1, 2020. Update to version 2019-07 and replace the following deprecated API calls to avoid breaking changes."

The page filter has been removed. Please use cursor-based pagination instead.

The featured field has been removed from the Collects resource

I am just wondering if this is something that is in the pipeline to fix in this repo or if it requires more developers to work on this?

Thanks

**Comment by donutdan4114** [comment]
Cursor pagination will definitely be supported before April 2020. At this point I'm not 100% sure if this will be a breaking change or will be totally backwards compatible. If there are breaking changes I will setup releases for different versions of the Shopify API.

**Comment by joehuggans** [comment]
Hi Dan, 
Will this mean myself and anyone else can now use the latest library with Drupal 8 and this will make it safe when the API versioning changes come in in 2 months?

**Comment by donutdan4114** [comment]
The update should be backwards compatible as far as pagination is concerned (unless there is custom code that uses pagination numbers to make API calls).

I'm not sure about the "collects featured field" issue. We are currently looking to get at least one other co-maintainer for the Shopify Drupal module to help with these kinds of issues. If you or anyone else wants to help on the Drupal side of things that'd be fantastic! I just don't have time to work with it anymore.

**Comment by donutdan4114** [comment]
I have pushed a new branch for the **2020-01** release. If you or anyone else wants to try it out and let me know if there are any issues that'd be great before I make an official release.

https://github.com/donutdan4114/shopify/tree/2020-01-pre-release

**Comment by squatto** [comment]
@donutdan4114 nice work! Thanks for pushing that. Have you had any testers yet? I'd be happy to help out.

**Comment by donutdan4114** [comment]
@squatto No one else has responded yet, so I'll assume no one else has checked it out yet :)

All I can say is that I've been using the new version on one my applications and it appears to work as intended.

**Comment by joehuggans** [comment]
@donutdan4114 - I will be working on this with Drupal 8 next week so will report back. The Shopify API doesn't look like it will require any modification, just the Shopify eCommerce module, would you agree?

**Comment by donutdan4114** [comment]
@joehuggans  I believe that is correct but honestly I haven't touched the code in years so don't take my word for it.

**Comment by joecampo** [comment]
@donutdan4114 Hey Dan - just wanted to drop in and say thank you! Just implemented the new version of getResourcePager and everything is working flawlessly on this new branch.

**Comment by feeloow** [comment]
Thank you for this update, I deployed it yesterday on first site (seems ok), othe deployments coming today and next monday.

**Comment by lesichkovm** [comment]
Hi @donutdan4114 all working fine with the new branch. 
Would you be able to publish it as a new release, to be referenced in composer. Not like currently: "donutdan4114/shopify": "dev-2020-01-pre-release"

**Comment by donutdan4114** [comment]
@lesichkovm Release has been created, let me know if it doesn't work for you!

**Comment by lesichkovm** [comment]
Thank you @donutdan4114
