### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by slince** [donutdan4114/shopify#7]
Hi, is there any plan to release a stable version?

**Comment by ry167** [comment]
This appears to be 'stable' as far as the code seems, though you can fork it and make a tag yourself if you like so that dev-master doesn't update on your codebase?

**Comment by panoply** [comment]
I'm using this in production. It's stable.

**Comment by slince** [comment]
@ry167  @panoply  Hi i have created a new repo https://github.com/slince/shopify-api-php  :grin:

**Comment by ry167** [comment]
@slince That doesn't look like a fork of this...

**Comment by panoply** [comment]
@slince PHP is dead these days anyway, learn Elixir. It's faster and better.

**Comment by slince** [comment]
@ry167  Yes, its new repo;
@panoply  I have to think about job opportunities, php is more popular in China :sweat_smile:
